collections:
    locs: 
        output: true
        permalink: /:title
    fish:
        output: true
        permalink: /:title


defaults:
    - scope:
        path: ""
      values:
        layout: default